const USER_TYPES = {
  SET_USERNAME: "SET_USERNAME",
  SET_IS_LOGGED_IN: "SET_IS_LOGGED_IN",
  SET_NAME: "SET_NAME",
  SET_PICTURE: "SET_PICTURE",
  SET_STATUS: "SET_STATUS",
  SET_PHONENUMBER: "SET_PHONENUMBER",
};

export { USER_TYPES };
